### ISSUE TITLE
User Experience and UI is horrible

### ISSUE THREAD

**Issue by developerfromjokela** [digabi/naksu#45]
UI and its UX is horrible, and not logical.

**Comment by mplattu** [comment]
Thanks for the feedback @developerfromjokela. Typically the bug reports or comments we get specify the exact problem and possibly, a solution for this. In this case you could point out which use case or action is not logical and with which changes you'd correct that. We also accept pull requests.

Before submitting your suggestion, please note that since we want to write cross-platform code our UI is written using [libui](https://github.com/andlabs/libui). This somewhat limits the elements and the aesthetic freedom we have in this project.

**Comment by developerfromjokela** [comment]
@mplattu https://github.com/fyne-io/fyne

Alternatives exist for libui

**Comment by mplattu** [comment]
Thanks again for your feedback. Of course there are alternatives for libui and alternatives for Go. At this point and based on this feedback we're not investing to Naksu UI. The current goals for the project can be read from [this blogpost](https://www.ylioppilastutkinto.fi/ajankohtaista/blogitekstit/970-Digitaalinen%20ylioppilastutkinto%20kehittyy%20koronan%20varjossa).

Of course, you're free to fork Naksu and rewrite it with your favourite UI library.

I will close the case but don't hesitate to reopen if you have any specific drawbacks or bugs concerning Naksu app.
